---
# tasks file for install-check_mk-agent (FreeBSD only)
- name: Create monitoring group | GROUP
  group:
    name: "{{ install_check_mk_agent_user }}"
    state: present
  tags:
    - install-check-mk-agent
- name: Create monitoring user | USER
  user:
    name: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    home: "{{ install_check_mk_agent_home }}"
    comment: "Check_MK Agent"
  tags:
    - install-check-mk-agent
- name: Copy check_mk_agent and set executable | TEMPLATE
  template:
    owner: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    mode: 0755
    src: check_mk_agent.freebsd.j2
    dest: "{{ install_check_mk_agent_home }}/check_mk_agent"
  tags:
    - install-check-mk-agent
- name: Grant sudo for check_mk_agent to monitoring user | TEMPLATE
  template:
    owner: root
    group: wheel
    mode: 0440
    src: 99_cmkagent.j2
    dest: /usr/local/etc/sudoers.d/99_cmkagent
    validate: 'visudo -cf %s'
  tags:
    - install-check-mk-agent
- name: Create directory - .ssh | FILE
  file:
    owner: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    mode: 0700
    path: "{{ install_check_mk_agent_home }}/.ssh"
    state: directory
  tags:
    - install-check-mk-agent
- name: Copy public key to .ssh/authorized_keys | TEMPLATE
  template:
    owner: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    mode: 0600
    src: "{{ install_check_mk_agent_authorized_keys }}"
    dest: "{{ install_check_mk_agent_home }}/.ssh/authorized_keys"
  tags:
    - install-check-mk-agent
- name: Create directory - local | FILE
  file:
    owner: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    mode: 0700
    path: "{{ install_check_mk_agent_home }}/local"
    state: directory
  tags:
    - install-check-mk-agent
- name: Generate local checks | TEMPLATE
  template:
    owner: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    mode: 0700
    src: "{{ item }}.j2"
    dest: "{{ install_check_mk_agent_home }}/local/{{ item }}"
  with_items: "{{ install_check_mk_agent_local_checks }}"
  tags:
    - install-check-mk-agent
- name: Create directory - plugins | FILE
  file:
    owner: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    mode: 0700
    path: "{{ install_check_mk_agent_home }}/plugins"
    state: directory
  tags:
    - install-check-mk-agent
- name: Generate plugins | TEMPLATE
  template:
    owner: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    mode: 0700
    src: "{{ item }}.j2"
    dest: "{{ install_check_mk_agent_home }}/plugins/{{ item }}"
  with_items: "{{ install_check_mk_agent_freebsd_plugins }}"
  tags:
    - install-check-mk-agent
- name: Create directory - spool | FILE
  file:
    owner: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    mode: 0700
    path: "{{ install_check_mk_agent_home }}/spool"
    state: directory
  tags:
    - install-check-mk-agent
- name: Create directory - cache | FILE
  file:
    owner: "{{ install_check_mk_agent_user }}"
    group: "{{ install_check_mk_agent_user }}"
    mode: 0700
    path: "{{ install_check_mk_agent_home }}/cache"
    state: directory
  tags:
    - install-check-mk-agent
...